// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../packages/FsCheck.2.7.1/lib/net45/FsCheck.dll"
#r "../packages/FsCheck.NUnit.2.7.1/lib/net45/FsCheck.NUnit.dll"
#r "../packages/NUnit.3.6.1/lib/net45/nunit.framework.dll"
#r "../packages/Argu.3.2.0/lib/net40/Argu.dll"
#r "../packages/Expecto.4.0.3/lib/net40/Expecto.dll"
#r "../packages/Expecto.FsCheck.4.0.3/lib/net40/Expecto.FsCheck.dll"
#r "../packages/Mono.Cecil.0.9.6.4/lib/net45/Mono.Cecil.dll"
#r "../packages/Mono.Cecil.0.9.6.4/lib/net45/Mono.Cecil.Mdb.dll"
#r "../packages/Mono.Cecil.0.9.6.4/lib/net45/Mono.Cecil.Pdb.dll"
#r "../packages/Mono.Cecil.0.9.6.4/lib/net45/Mono.Cecil.Rocks.dll"
#r "../UserInterface/node_modules/fable-core/Fable.Core.dll"