// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../InstructionType.fs"
      "../MachineState.fs"
      "../EmulatorHelper.fs"
      "../SFInstruction.fs"
      "../ALUInstruction.fs"
      "../MEMInstruction.fs"
      "../SHIFTInstruction.fs"
      "../LABELInstruction.fs"
      "../BRANCHInstruction.fs"
      "../Cast.fs"
      "../Emulator.fs"
      "../Parser.fs"
      "../Program.fs"
      "../UserInterface.fs"
